import type { FormGroupDemoOptions } from './FormGroupControls';

export function formGroupUsage({ hint, hintColor, error }: FormGroupDemoOptions) {
  return [
    "import { Button } from './components/Button/Button';",
    "import { FormGroup } from './components/FormGroup/FormGroup';",
    "import { Label } from './components/Label/Label';",
    "import { PasswordField } from './components/PasswordField/PasswordField';",
    "import { TextField } from './components/TextField/TextField';",
    '',
    'export function SignInForm() {',
    '  return (',
    '    <form',
    '      onSubmit={(event) => {',
    '        event.preventDefault();',
    "        window.alert('Form submitted');",
    '      }}',
    '    >',
    '      <FormGroup',
    `        hint={${JSON.stringify(hint)}}`,
    `        hintColor={${JSON.stringify(hintColor)}}`,
    `        error={${JSON.stringify(error)}}`,
    '        hintId="username-hint"',
    '      >',
    '        <Label for="username">Username</Label>',
    '        <TextField',
    '          id="username"',
    '          name="username"',
    '          placeholder="Enter your username"',
    '          ariaDescribedBy="username-hint"',
    '        />',
    '      </FormGroup>',
    '      <FormGroup hint="Keep your password private." hintId="password-hint">',
    '        <Label for="password">Password</Label>',
    '        <PasswordField',
    '          id="password"',
    '          name="password"',
    '          placeholder="Enter your password"',
    '          ariaDescribedBy="password-hint"',
    '        />',
    '      </FormGroup>',
    '      <Button type="submit">Sign in</Button>',
    '    </form>',
    '  );',
    '}',
  ].join('\n');
}
